### TEST ROUTE
GET http://localhost:8080/


### GET ALL USERS
GET http://localhost:8080/users

### GET USER BY ID
GET http://localhost:8080/users/60

### CREATE USER
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "full_name": "test name",
    "email": "test@gmail.com",
    "contact_phone": "0712345678",
    "address": "1234, Embu",
    "role": "user",
    "password": "password1"
}

### UPDATE USER BY ID
PUT http://localhost:8080/users/8 HTTP/1.1
Content-Type: application/json

{
    "full_name": "test kabish ",
    "email": "test57@gmail.com",
    "contact_phone": "0712345678",
    "address": "1234, Embu",
    "role": "user",
    "password": "testpass"
}	

### DELETE USER BY ID
DELETE http://localhost:8080/users/90


### GET ALL VEHICLE SPECIFICATIONS
GET http://localhost:8080/vehicleSpecifications

### GET VEHICLE SPECIFICATION BY ID
GET http://localhost:8080/vehicleSpecifications/3

### CREATE VEHICLE SPECIFICATION
POST http://localhost:8080/vehicleSpecifications HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "Toyotaaa",
    "model": "Corollaaa",
    "year": 2018,
    "fuel_type": "Petrolaa",
    "engine_capacity": "1800cc",
    "transmission": "Automatic",
    "seating_capacity": 5,
    "color": "White",
    "features": "Air Conditioning, Power Steering, Anti-lock Braking System"
}

### UPDATE VEHICLE SPECIFICATION BY ID
PUT http://localhost:8080/vehicleSpecifications/3 HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "Toaaa",
    "model": "Cache-Control: ",
    "year": 2018,
    "fuel_type": "Paaaet",
    "engine_capacity": "1800cc",
    "transmission": "Autom",
    "seating_capacity": 5,
    "color": "White",
    "features": "Air Conditioning"
}

### DELETE VEHICLE SPECIFICATION BY ID
DELETE http://localhost:8080/vehicleSpecifications/3




### GET ALL VEHICLES
GET http://localhost:8080/vehicles

### GET VEHICLE BY ID
GET http://localhost:8080/vehicles/3

### CREATE VEHICLE
POST http://localhost:8080/vehicles HTTP/1.1
Content-Type: application/json

{
    "vehicleSpec_id": 1,
    "rental_rate": "50.00",
    "availability": false
}

### UPDATE VEHICLE BY ID
PUT http://localhost:8080/vehicles/3 HTTP/1.1
Content-Type: application/json

{
    "vehicleSpec_id": 1,
    "rental_rate": "5000.00",
    "availability": true
}

### DELETE VEHICLE BY ID
DELETE http://localhost:8080/vehicles/3

