### TEST ROUTE
GET http://localhost:8080/


### GET ALL USERS
GET http://localhost:8080/users

### GET USER BY ID
GET http://localhost:8080/users/60

### CREATE USER
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "full_name": "test name",
    "email": "test@gmail.com",
    "contact_phone": "0712345678",
    "address": "1234, Embu",
    "role": "user",
    "password": "password1"
}

### UPDATE USER BY ID
PUT http://localhost:8080/users/8 HTTP/1.1
Content-Type: application/json

{
    "full_name": "test kabish ",
    "email": "test57@gmail.com",
    "contact_phone": "0712345678",
    "address": "1234, Embu",
    "role": "user",
    "password": "testpass"
}	

### DELETE USER BY ID
DELETE http://localhost:8080/users/90


### GET ALL VEHICLE SPECIFICATIONS
GET http://localhost:8080/vehicleSpecifications

### GET VEHICLE SPECIFICATION BY ID
GET http://localhost:8080/vehicleSpecifications/3

### CREATE VEHICLE SPECIFICATION
POST http://localhost:8080/vehicleSpecifications HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "Toyotaaa",
    "model": "Corollaaa",
    "year": 2018,
    "fuel_type": "Petrolaa",
    "engine_capacity": "1800cc",
    "transmission": "Automatic",
    "seating_capacity": 5,
    "color": "White",
    "features": "Air Conditioning, Power Steering, Anti-lock Braking System"
}

### UPDATE VEHICLE SPECIFICATION BY ID
PUT http://localhost:8080/vehicleSpecifications/3 HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "Toaaa",
    "model": "Cache-Control: ",
    "year": 2018,
    "fuel_type": "Paaaet",
    "engine_capacity": "1800cc",
    "transmission": "Autom",
    "seating_capacity": 5,
    "color": "White",
    "features": "Air Conditioning"
}

### DELETE VEHICLE SPECIFICATION BY ID
DELETE http://localhost:8080/vehicleSpecifications/3




### GET ALL VEHICLES
GET http://localhost:8080/vehicles

### GET VEHICLE BY ID
GET http://localhost:8080/vehicles/3

### CREATE VEHICLE
POST http://localhost:8080/vehicles HTTP/1.1
Content-Type: application/json

{
    "vehicleSpec_id": 1,
    "rental_rate": "50.00",
    "availability": false
}

### UPDATE VEHICLE BY ID
PUT http://localhost:8080/vehicles/3 HTTP/1.1
Content-Type: application/json

{
    "vehicleSpec_id": 1,
    "rental_rate": "5000.00",
    "availability": true
}

### DELETE VEHICLE BY ID
DELETE http://localhost:8080/vehicles/3


### GET ALL LOCATIONS
GET http://localhost:8080/locations

### GET LOCATION BY ID
GET http://localhost:8080/locations/3

### CREATE LOCATION

POST http://localhost:8080/locations HTTP/1.1
Content-Type: application/json

{
    "name": "Nairobi HEEEY  Branch",
    "address": "1234 Main St, Nairobi",
    "contact_phone": "0712345678"
}

### UPDATE LOCATION BY ID
PUT http://localhost:8080/locations/3 HTTP/1.1
Content-Type: application/json

{
    "name": "Nairobi Branch",
    "address": "1234 Main St, Nairobi",
    "contact_phone": "0712345678"
}

### DELETE LOCATION BY ID
DELETE http://localhost:8080/locations/3


### GET ALL BOOKINGS
GET http://localhost:8080/bookings

### GET BOOKING BY ID
GET http://localhost:8080/bookings/4

### CREATE BOOKING
POST http://localhost:8080/bookings HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "vehicle_id": 1,
    "location_id": 1,
    "booking_date": "2021-06-01",
    "return_date": "2021-06-08",
    "total_amount": "36.00",
    "booking_status": "reaaly"
}

### UPDATE BOOKING BY ID
PUT http://localhost:8080/bookings/4 HTTP/1.1
Content-Type: application/json

{
    "user_id": 1,
    "vehicle_id": 1,
    "location_id": 1,
    "booking_date": "2021-06-01",
    "return_date": "2021-06-10",
    "total_amount": "36000.00",
    "booking_status": "reaaaaaaaaaaaaaaaaaaly"
}

### DELETE BOOKING BY ID
DELETE http://localhost:8080/bookings/4



###PAYMENTS
### GET ALL PAYMENTS
GET http://localhost:8080/payments

### GET PAYMENT BY ID
GET http://localhost:8080/payments/3

### CREATE PAYMENT
POST http://localhost:8080/payments HTTP/1.1
Content-Type: application/json

{
    "booking_id": 1,
    "amount": "35000.00",
    "payment_status": "Completed hfg",
    "payment_date": "2021-06-01",
    "payment_method": "Credit Cardfddg",
    "transaction_id": "TXN123456"
}

### UPDATE PAYMENT BY ID
PUT http://localhost:8080/payments/3 HTTP/1.1
Content-Type: application/json

{
    "booking_id": 1,
    "amount": "35000.00",
    "payment_status": "Comple",
    "payment_date": "2021-06-01",
    "payment_method": "Credit",
    "transaction_id": "TXN123456"
}

### DELETE PAYMENT BY ID
DELETE http://localhost:8080/payments/3
